<?php
    $this->headTitle($this->title);
    
    $arrUrlEdit=array('controller'=>$this->urlController,'action' =>'edit',$this->campoPK => $this->id);
    $url_edit=$this->url($this->urlBase,$arrUrlEdit);
    
    $form->setAttribute('action',$url_edit);
    $form->prepare();

    $arrUrlEdit['action']='delete';
    $url_delete=$this->url($this->urlBase,$arrUrlEdit);
        
    echo $this->partial($this->partialForm,
                        array('form' => $form,
                              'title'=>$this->title,
                              'formFieldsWidth'=> $this->formFieldsWidth,
                              'urlDelete' =>$url_delete,
                              'urlController' => $this->urlController,
                              'formRequireDatePicker' =>$this->formRequireDatePicker,
                              'formRequireSelect2' =>$this->formRequireSelect2,
                              'formJsFile' =>$this->formJsFile,
                              )
                        );
?>