<?php $url= $urlSort=$this->url($this->urlBase,['controller'=>$this->urlController]);?>
<table class="table table-striped">
<tr>
    <?=$this->renderTableHeaderList($this->list_titles,$this->list_fields,$url,$this->arrSort)?>
</tr>

<?php 
   $countRecords=0; 
   foreach ($this->paginator as $reg){ 
        $countRecords++;
        $campoPk = $this->campoPK;    
        $id=$reg->$campoPk;
        $arrUrlEdit=['controller'=>$this->urlController,'action'=>'edit',$campoPk=>$id];
        $arrUrlDel=['controller'=>$this->urlController,'action'=>'delete',$campoPk=>$id];

        $url_edit=$this->url($this->urlBase,$arrUrlEdit);
        $url_delete=$this->url($this->urlBase,$arrUrlDel);  
?>    

        <tr>
            <?php foreach ($this->list_fields as $field): 
                 $getter = 'get'. ucfirst($field);
                 if (is_bool($reg->$field) === true) $value = ($reg->$field === true) ? "Si":"No";
                 else $value= $reg->$getter();
            ?>
                <td><?= $value ?></td>
            <?php endforeach; ?>
            <td>
                <?= $this->renderLinkEdit($url_edit); ?>
                <?= $this->renderLinkDelete($url_delete); ?>
            </td>
        </tr>
<?php } //endforeach; ?>
</table>
<strong><?= $countRecords?></strong> Registros