<!-- Begin Catalogo Modal -->
<div id="myModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 class="modal-title" id="myModalLabel">Catalogo</h3>
      </div>
      <div class="modal-body" style="height: 150px; overflow:auto">
      </div>
      <div class="modal-footer">
        <button class="btn btn-default" data-dismiss="modal">Aceptar</button>
      </div>
    </div>
  </div>
</div>
<!-- End Catalogo Modal -->